### ISSUE TITLE
Test on Packet.net Type 2A server and update documentation to match

### ISSUE THREAD

**Issue by vielmetti** [elraro/gitlab-ce-omnibus-armv8#1]
I'll set a task for myself to test this on the Packet Type 2A (96-core Cavium) bare metal server, and will report back with results.

**Comment by elraro** [comment]
Great, thanks! I need to finish the compile script and make a wiki or something

**Comment by vielmetti** [comment]
A fresh reconfigure on bare metal worked, after doing `apt-get install tzdata`. I understand that's taken care of in a new gemfile. 

The root cause was https://bugs.launchpad.net/cloud-images/+bug/1682305 (Ubuntu removes tzdata and locale info in LTS release).

**Comment by vielmetti** [comment]
Worth mentioning (so that's it's easier to find) that there's an active discussion at https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1625
